#!/bin/bash
#
# Wraps apt-get so we can notify Slack
#

if [[ $@ == *dist-upgrade* && $@ != *-d* ]] ; then
  if [ -x /usr/lib/update-notifier/update-motd-reboot-required ]; then
    REBOOTMSG=" and *reboot is required*"
  else
    REBOOTMSG=""
  fi
  /usr/bin/apt-get $@ && /usr/local/bin/apt_notify_slack "\`dist-upgrade\` was *successful*${REBOOTMSG}" || /usr/local/bin/apt_notify_slack "\`dist-upgrade\` was *unsuccessful*"
elif [[ $@ == *update* ]] ; then
  /usr/bin/apt-get $@ || /usr/local/bin/apt_notify_slack "\`update\` was *unsuccessful*"
else
  /usr/bin/apt-get $@
fi
