default['cronapt']['mailto']           = 'your@email.com'
default['cronapt']['mailon']           = 'always'
default['cronapt']['aptcommand']       = '/usr/local/bin/apt-get-slack'
default['cronapt']['enable_upgrade']   = false
default['cronapt']['force_confmiss']   = false
default['cronapt']['force_confnew']    = false
default['cronapt']['force_confdef']    = false
default['cronapt']['force_confold']    = false
default['cronapt']['keepupdated']      = %w(bash openssl)
default['cronapt']['environment']      = false
